=== Darkazazello/Diplom/fault.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <!--TODO add custom simple types of jump operation(maybe pattern is "w(r)/positin/value") and state value (maybe pattern
   is "Svalue")-->
    <xsd:element name="faults">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="fault" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="fault">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="state" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="name" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="state">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="jumpOperation" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="stateValue" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="jumpOperation">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="nextState" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="operation" type="xsd:string" use="required"/>
            <xsd:attribute name="position" type="xsd:int" use="required"/>
            <xsd:attribute name="value" type="xsd:string" use="required"/>

        </xsd:complexType>
    </xsd:element>


    <xsd:element name="nextState">
        <xsd:complexType>
            <xsd:attribute name="stateValue" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>


</xsd:schema>

=== Darkazazello/Diplom/ParserXML/src/main/xml/example/fault.xml
<?xml version="1.0" encoding="utf-8"?>
<faults xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fault.xsd">
    <fault name="Normal">
        <state stateValue="0">
            <jumpOperation operation="w" position="0" value="1">
                <nextState stateValue="1" />
            </jumpOperation>
        </state>
        <state stateValue="1">
            <jumpOperation operation="w" position="0" value="0">
                <nextState stateValue="0" />
            </jumpOperation>
       </state>
    </fault>
    <fault name="SA0">
        <state stateValue="0">
            <jumpOperation operation="w" position="0" value="1">
                <nextState stateValue="0"/>
            </jumpOperation>
            <jumpOperation operation="w" position="0" value="0">
                <nextState stateValue="0" />
            </jumpOperation>
        </state>
    </fault>
</faults>
